// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1ncVghBtsvL-ElZauTk_5NXhg-PEgwSI',
    appId: '1:480411534440:android:4e5bf38691cf6322a067dd',
    messagingSenderId: '480411534440',
    projectId: 'symmetry-news-app-5dcc3',
    storageBucket: 'symmetry-news-app-5dcc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJtSi8L9fiL3tS6HSQiNyhwwBl7MnNx8s',
    appId: '1:480411534440:ios:595745482dd63faea067dd',
    messagingSenderId: '480411534440',
    projectId: 'symmetry-news-app-5dcc3',
    storageBucket: 'symmetry-news-app-5dcc3.firebasestorage.app',
    iosBundleId: 'com.example.newsAppCleanArchitecture',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQG5zaylradO5kuHGKrH4VawinEgPp17o',
    appId: '1:480411534440:web:f8a4a0ad0c4f726fa067dd',
    messagingSenderId: '480411534440',
    projectId: 'symmetry-news-app-5dcc3',
    authDomain: 'symmetry-news-app-5dcc3.firebaseapp.com',
    storageBucket: 'symmetry-news-app-5dcc3.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJtSi8L9fiL3tS6HSQiNyhwwBl7MnNx8s',
    appId: '1:480411534440:ios:595745482dd63faea067dd',
    messagingSenderId: '480411534440',
    projectId: 'symmetry-news-app-5dcc3',
    storageBucket: 'symmetry-news-app-5dcc3.firebasestorage.app',
    iosBundleId: 'com.example.newsAppCleanArchitecture',
  );

}